/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7d04758a-69b8-40de-a6ee-d3955d22e59b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r9bxftqeT",
    "aws_user_pools_web_client_id": "73nasihtnavupfenoc61b049n7",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://42tmmwpz7zfjjajkibimss2ex4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-6vzzebkj6fhk7ll73smzbfgtpi",
    "aws_cloud_logic_custom": [
        {
            "name": "partyusREST",
            "endpoint": "https://q4r8pc2ayl.execute-api.us-east-1.amazonaws.com/production",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "partyus82c6ea2e2f6c45ebad64781aaf5ec02d102116-production",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
