/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eaaaac5c-0ceb-4a1c-8cb2-1b7227dd170c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_d05p3wR1X",
    "aws_user_pools_web_client_id": "1ho0osism0m87cn23itgbgvana",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://2pquj4yd5rhidh4d422ctjt36y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-bskp7sfdujbr5onwjvgmxa3efa",
    "aws_cloud_logic_custom": [
        {
            "name": "partyusREST",
            "endpoint": "https://jmlzdyhu0k.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "partyus82c6ea2e2f6c45ebad64781aaf5ec02d225309-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
